table Pedidos
	lineageTag: ddb7e851-b659-5c96-a8a1-37335cf274d9

	measure 'Pedidos totales' = COUNTROWS(Pedidos)
		formatString: #,0
		lineageTag: b5bdda9c-71f3-5a58-a34c-7e4197205c7f

	measure Ingresos = SUM(Pedidos[valor_total])
		formatString: #,0
		lineageTag: ddf8809b-b292-5fb2-8c3c-c9180317e538

	measure 'Ticket medio' = DIVIDE([Ingresos], [Pedidos totales])
		formatString: #,0.00
		lineageTag: b297a8e4-cc4e-537d-abc5-ce686330908b

	measure 'Clientes únicos' = DISTINCTCOUNT(Pedidos[customer_unique_id])
		formatString: #,0
		lineageTag: 5c1fdd9b-d3ed-5524-b04a-3c436e349ddc

	measure '% Clientes que repiten' = DIVIDE(COUNTROWS(FILTER(VALUES(Pedidos[customer_unique_id]), CALCULATE(COUNTROWS(Pedidos)) >= 2)), [Clientes únicos])
		formatString: 0.0%
		lineageTag: 351c15e2-c234-54a7-a8d1-7fbacb0456f3

	measure 'Nota media' = AVERAGE(Pedidos[review_score])
		formatString: 0.00
		lineageTag: b63d64ef-bc39-5064-9573-b93be219cc4f

	measure '% Mala nota' = DIVIDE(CALCULATE(COUNTROWS(Pedidos), Pedidos[review_score] >= 1 && Pedidos[review_score] <= 2), CALCULATE(COUNTROWS(Pedidos), NOT ISBLANK(Pedidos[review_score])))
		formatString: 0.0%
		lineageTag: a04a2773-c4fb-5814-9d0d-8a441c9976f7

	measure '% Retraso' = DIVIDE(CALCULATE(COUNTROWS(Pedidos), Pedidos[con_retraso] = TRUE()), [Pedidos totales])
		formatString: 0.0%
		lineageTag: 1018f1d4-cc62-5ba6-a2d0-939b2479d5c0

	measure 'Días de entrega' = AVERAGE(Pedidos[dias_entrega])
		formatString: 0.0
		lineageTag: 7dd6a673-391e-59cb-bb4c-ba4c3d0fe13c

	measure '% Mala nota (mín. 100 pedidos)' = IF([Pedidos totales] >= 100, [% Mala nota])
		formatString: 0.0%
		lineageTag: f6261b31-aa99-5877-bb00-baaea630905c

	measure 'Pedidos con mala nota' = CALCULATE(COUNTROWS(Pedidos), Pedidos[review_score] >= 1 && Pedidos[review_score] <= 2)
		formatString: #,0
		lineageTag: 1b24137d-ab1f-5a99-8f75-444e15f9eb39

	column order_id
		dataType: string
		lineageTag: 2c52d169-d6a4-53ba-8f1c-259491656600
		summarizeBy: none
		sourceColumn: order_id

	column customer_unique_id
		dataType: string
		lineageTag: 058a04f0-66b7-59a0-9584-5e588f88501e
		summarizeBy: none
		sourceColumn: customer_unique_id

	column customer_state
		dataType: string
		lineageTag: f8d35c44-8bde-5917-94e6-75c0dbb10e4f
		summarizeBy: none
		sourceColumn: customer_state

	column categoria_principal
		dataType: string
		lineageTag: 896947b2-0b17-5efe-8c14-e716a2e5a8ed
		summarizeBy: none
		sourceColumn: categoria_principal

	column tipo_pago
		dataType: string
		lineageTag: 4172b480-11df-5d15-a2ab-38cfdeefeb5a
		summarizeBy: none
		sourceColumn: tipo_pago

	column n_items
		dataType: double
		lineageTag: 77517348-b358-59a0-aec6-60b103f08653
		summarizeBy: none
		sourceColumn: n_items

	column n_vendedores
		dataType: double
		lineageTag: 5c5652d3-d09f-5db9-9a2b-49b37f1cfd63
		summarizeBy: none
		sourceColumn: n_vendedores

	column valor_productos
		dataType: double
		lineageTag: 913a38f8-d0fd-5754-bd15-052e8905c9b1
		summarizeBy: none
		sourceColumn: valor_productos

	column valor_envio
		dataType: double
		lineageTag: 0e2c51d9-1d77-5f3c-9d39-fb2d8d6d5a1e
		summarizeBy: none
		sourceColumn: valor_envio

	column valor_total
		dataType: double
		lineageTag: b1dff6ab-2587-57e2-81ad-fe7839ca6c0a
		summarizeBy: none
		sourceColumn: valor_total

	column review_score
		dataType: double
		lineageTag: e7683469-1dff-5265-b6c6-e89e2458163e
		summarizeBy: none
		sourceColumn: review_score

	column dias_entrega
		dataType: double
		lineageTag: a45aa756-dca9-5cd4-9e5a-029fb5900c80
		summarizeBy: none
		sourceColumn: dias_entrega

	column dias_vs_estimado
		dataType: double
		lineageTag: 43ec9128-3293-553a-8ae4-e0af1c1ab582
		summarizeBy: none
		sourceColumn: dias_vs_estimado

	column con_retraso
		dataType: boolean
		lineageTag: c33df1ea-9a51-5652-b965-e577686b9df5
		summarizeBy: none
		sourceColumn: con_retraso

	column fecha_compra
		dataType: dateTime
		formatString: dd/MM/yyyy
		lineageTag: 6990bf85-df62-594b-86b9-8b93a6ab3607
		summarizeBy: none
		sourceColumn: fecha_compra

		annotation UnderlyingDateTimeDataType = Date

	column tramo_entrega
		dataType: string
		lineageTag: 0c822cfc-24b3-570e-8863-1b64127ca1ca
		summarizeBy: none
		sourceColumn: tramo_entrega
		sortByColumn: tramo_orden

	column tramo_orden
		dataType: int64
		lineageTag: 4c204737-4338-5546-b759-be3bd0fd58ee
		summarizeBy: none
		sourceColumn: tramo_orden

	column tipo_pedido
		dataType: string
		lineageTag: 84fe3cbb-8c19-59c3-a4aa-935ef22f2929
		summarizeBy: none
		sourceColumn: tipo_pedido

	partition Pedidos = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaDatos & "pedidos.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Columnas = Table.SelectColumns(Encabezados, {"order_id", "customer_unique_id", "customer_state", "categoria_principal", "tipo_pago", "order_purchase_timestamp", "n_items", "n_vendedores", "valor_productos", "valor_envio", "valor_total", "review_score", "dias_entrega", "dias_vs_estimado", "con_retraso"}),
				    Tipos = Table.TransformColumnTypes(Columnas, {{"order_purchase_timestamp", type datetime}, {"n_items", type number}, {"n_vendedores", type number}, {"valor_productos", type number}, {"valor_envio", type number}, {"valor_total", type number}, {"review_score", type number}, {"dias_entrega", type number}, {"dias_vs_estimado", type number}, {"con_retraso", type logical}}, "en-US"),
				    Fecha = Table.AddColumn(Tipos, "fecha_compra", each DateTime.Date([order_purchase_timestamp]), type date),
				    Tramo = Table.AddColumn(Fecha, "tramo_entrega", each if [dias_vs_estimado] <= 0 then "A tiempo" else if [dias_vs_estimado] <= 3 then "1-3 días tarde" else if [dias_vs_estimado] <= 7 then "4-7 días tarde" else "Más de 7 días tarde", type text),
				    TramoOrden = Table.AddColumn(Tramo, "tramo_orden", each if [dias_vs_estimado] <= 0 then 1 else if [dias_vs_estimado] <= 3 then 2 else if [dias_vs_estimado] <= 7 then 3 else 4, Int64.Type),
				    TipoPedido = Table.AddColumn(TramoOrden, "tipo_pedido", each if [n_vendedores] >= 2 then "Varios vendedores" else if [n_items] >= 2 then "Varios productos, 1 vendedor" else "1 producto", type text),
				    Final = Table.RemoveColumns(TipoPedido, {"order_purchase_timestamp"})
				in
				    Final

	annotation PBI_ResultType = Table

